### ISSUE TITLE
Copying an article with columnset doesn't work

### ISSUE THREAD

**Issue by Olli** [contao-bootstrap/grid-editor#10]
I have an article with 2 columns.
The copy of the article has the first column with the BS classes but the second column has no BS classes and the comment "" but there is no third.
After saving the column set in the copied article again it works as expected.

**Comment by dmolineus** [comment]
I assume you are using subcolumns which probably causes the issue. To evaluate it please install only subcolumns (no contao bootstrap) and duplicate the article again. I think there will be the save behaviour.

**Comment by Olli** [comment]
A plain subcolumns doesn't show such a behavior. I'd test it.

**Comment by dmolineus** [comment]
Cannot reproduce it. And there is no technical reason why it should not work.
