### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by bschi** [contao-bootstrap/grid-editor#11]
Hallo, ich würde gerne Bootstrap 4 verwenden, das aktuelle Spaltenset unterstützt derzeit kein xl. Ist es möglich, dies zu integrieren? Für Bootstrap 3 wäre es ja nicht schlimm, wenn ggf. diese Klassen zusätzlich im Frontend erscheinen, die werden ja nicht gerendert und demnach gibt es auch keine Layoutverschiebungen.

**Comment by dmolineus** [comment]
Grundsätzlich möglich ist dies schon, hängt aber stark von der Grundsatzentscheidung einer BS 4 Unterstützung des gesamten Pakets ab.

**Comment by dmolineus** [comment]
Geschlossen, da abhängig von contao-bootstrap/bundle#2
