### ISSUE TITLE
Contao 3.5.4 & Composer: The module dependencies could not be resolved.

### ISSUE THREAD

**Issue by Webstylerin** [contao-bootstrap/grid-editor#12]
Hallo!

Sobald ich die Erweiterung über den Composer installiere und auf Pakete aktualisieren klicke bekomme ich folgende Meldung:

The module dependencies could not be resolved.
Array
(
    [bootstrap-grid] => Array
        (
            [0] => core
            [1] => bootstrap-core
        )

)

Habe auch versucht vorher bootstrap-core zu installieren, bringt aber das gleiche Problem. :(

Scheint auch noch andere mit ähnlichen Problemem zu geben: https://community.contao.org/de/showthread.php?59556-The-module-dependencies-could-not-be-resolved&highlight=The+module+dependencies+could+resolved.

VG
Nicole

**Comment by Webstylerin** [comment]
Habs jetzt mit nem Tipp aus einem anderen Thread (https://community.contao.org/de/showthread.php?58986-Fehler-beim-installieren&p=383186&viewfull=1#post383186) hinbekommen.

Habe die Erweiterung gelöscht und dann über Werkzeuge die Verknüpfungen neu erstellt.

Jetzt lass ich erst mal die Finger weg da es funktioniert. Ich nutze die Erweiterung aber öfter und kannte die Meldung bisher noch nicht und da ich ja den anderen aktuellen Thread mit 3.5.4 gefunden habe, dachte ich, es liegt auch am daran.

Nun gut, ich lass hier mal offen, falls es doch ein Problem bei der Installation gibt, ansonsten, einfach schließen und Entschuldigung für den Aufwand. :)

**Comment by dmolineus** [comment]
Das Problem hat nichts mit dem verlinkten Thread zu tun, sondern wohl mit https://github.com/contao-community-alliance/composer-plugin/issues/44. Da dies kein Problem der Bootstrap Extension ist, sondern ein generelles Problem der Composer-Integration in Contao und mit allen Updates auftreten kann, schließe ich hier mal das Ticket. Wenn möglich Feedback in den verlinkten Ticket geben.
