### ISSUE TITLE
Factory.php - fetch Db result

### ISSUE THREAD

**Issue by niebuhrhood** [contao-bootstrap/grid-editor#13]
Hi,

got an issue in factory.php. Im running Contao 3.5.6 and grid-editor 1.1.2, contao-community-alliance/event-dispatcher 1.3.0

error.log
```
Fatal error: Uncaught exception InvalidArgumentException with message Could not find columnset with ID "0" thrown in composer/vendor/contao-bootstrap/grid-editor/src/Factory.php on line 85

[14-Jan-2016 14:51:47 Europe/Berlin] PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Could not find columnset with ID "0"' thrown in /Users/path/to/contao-3.5.6-root/composer/vendor/contao-bootstrap/grid-editor/src/Factory.php on line 85
#0 /Users/path/to/contao-3.5.6-root/composer/vendor/contao-bootstrap/grid-editor/src/Factory.php(142): Netzmacht\Bootstrap\Grid\Factory::fetchResult('0')
#1 /Users/path/to/contao-3.5.6-root/composer/vendor/contao-bootstrap/grid-editor/src/Integration/Subcolumns.php(142): Netzmacht\Bootstrap\Grid\Factory::createById('0')
#2 /Users/path/to/contao-3.5.6-root/system/modules/core/forms/Form.php(197): Netzmacht\Bootstrap\Grid\Integration\Subcolumns->hookLoadFormField(Object(FelixPfeiffer\Subcolumns\FormColStart), 'auto_form_4', Array, Object(Contao\Form))
#3 /Users/path/to/contao-3.5.6-root/system/modules/core/classes/Hybrid.php(231): Contao\Form->compile()
#4 /Users/path/to/contao-3.5.6-root/system/modules/core/forms/Form.php(90): Contao\Hybrid->generate()
#5 /Users/path/to/contao-3.5.6-root/system/modules/core/library/Contao/Controller.php(476): Contao\Form->generate()
#6 /Users/path/to/contao-3.5.6-root/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#7 /Users/path/to/contao-3.5.6-root/system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#8 /Users/path/to/contao-3.5.6-root/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#9 /Users/path/to/contao-3.5.6-root/system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#10 /Users/path/to/contao-3.5.6-root/system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#11 /Users/path/to/contao-3.5.6-root/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#12 /Users/path/to/contao-3.5.6-root/system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#13 /Users/path/to/contao-3.5.6-root/index.php(20): Contao\FrontendIndex->run()
#14 {main}
```
FE and BE not working
When I comment line 84-86 in Factory.php

```
//if ($result->numRows < 1) {
    //throw new \InvalidArgumentException(sprintf('Could not find columnset with ID "%s"', $gridId));
//}
```
Its working when commented, but I dont know why?

This my copy from tl_columnset

````
1	0	1452770903	2 Spalten - 50% SM		2	a:1:{i:0;s:2:"sm";}	1	NULL	a:2:{i:0;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:0:"";}}	NULL	a:2:{i:0;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:0:"";}}	NULL	NULL	
2	0	1452770910	2 Spalten - 75% 25% SM		2	a:1:{i:0;s:2:"sm";}	1	NULL	a:2:{i:0;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:6:"push-1";}i:1;a:3:{s:5:"width";s:1:"4";s:6:"offset";s:0:"";s:5:"order";s:6:"push-2";}}	NULL	NULL	NULL	NULL	
3	0	1452770895	1 Spalte - 75% SM		1	a:1:{i:0;s:2:"sm";}	1	a:1:{i:0;a:2:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";}}	a:1:{i:0;a:3:{s:5:"width";s:1:"7";s:6:"offset";s:0:"";s:5:"order";s:0:"";}}	NULL	NULL	a:1:{i:0;a:5:{s:6:"column";s:1:"1";s:2:"xs";s:0:"";s:2:"sm";s:0:"";s:2:"md";s:0:"";s:2:"lg";s:0:"";}}	a:1:{i:0;a:2:{s:6:"column";s:1:"1";s:5:"class";s:0:"";}}	
4	0	1452770908	2 Spalten - 50% SM Abstand rechts		2	a:1:{i:0;s:2:"sm";}	1	NULL	a:2:{i:0;a:3:{s:5:"width";s:1:"6";s:6:"offset";s:0:"";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"5";s:6:"offset";s:1:"1";s:5:"order";s:0:"";}}	NULL	NULL	NULL	NULL	
5	0	1452770898	2 Spalten - 25% 75% SM		2	a:2:{i:0;s:2:"xs";i:1;s:2:"sm";}	1	a:2:{i:0;a:2:{s:5:"width";s:2:"12";s:6:"offset";s:0:"";}i:1;a:2:{s:5:"width";s:2:"12";s:6:"offset";s:0:"";}}	a:2:{i:0;a:3:{s:5:"width";s:1:"3";s:6:"offset";s:0:"";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"9";s:6:"offset";s:0:"";s:5:"order";s:0:"";}}	NULL	NULL	NULL	NULL	
6	0	1452770900	2 Spalten - 33% 66% SM		2	a:2:{i:0;s:2:"xs";i:1;s:2:"sm";}	1	a:2:{i:0;a:2:{s:5:"width";s:2:"12";s:6:"offset";s:0:"";}i:1;a:2:{s:5:"width";s:2:"12";s:6:"offset";s:0:"";}}	a:2:{i:0;a:3:{s:5:"width";s:1:"4";s:6:"offset";s:0:"";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"8";s:6:"offset";s:0:"";s:5:"order";s:0:"";}}	NULL	NULL	NULL	NULL	
9	0	1452770906	2 Spalten - 50% SM Abstand links rechts		2	a:1:{i:0;s:2:"sm";}	1	NULL	a:2:{i:0;a:3:{s:5:"width";s:1:"5";s:6:"offset";s:1:"1";s:5:"order";s:0:"";}i:1;a:3:{s:5:"width";s:1:"5";s:6:"offset";s:1:"1";s:5:"order";s:0:"";}}	NULL	NULL	NULL	NULL	
```
This issue began in update process from 3.4 to 3.5.6
In 3.5.4 there is no problem with grid-editor.

Anyone same issue with 3.5.6?

**Comment by dmolineus** [comment]
Seems like there is a form column set with an invalid columnset id.

**Comment by niebuhrhood** [comment]
Good hint!
I checked the columnsets in my form generator and resaved them.
Thanks

**Comment by BlackP999** [comment]
Hi,
ich habe das selbe Problem.
Bekomme folgende Meldung:
`PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Could not find columnset with ID "1"' thrown in /home/www/.../composer/vendor/contao-bootstrap/grid-editor/src/Factory.php on line 85
#0 /home/www/.../composer/vendor/contao-bootstrap/grid-editor/src/Factory.php(142): Netzmacht\Bootstrap\Grid\Factory::fetchResult('1')
#1 /home/www/.../system/modules/bootstrap-grid/templates/ce_colsetPart.html5(8): Netzmacht\Bootstrap\Grid\Factory::createById('1')
#2 /home/www/.../system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/www/xn--g...')
#3 /home/www/.../system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#4 /home/www/.../system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#5 /home/www/.../system/modules/core/elements/ContentElement.php(285): Contao\FrontendTemplate->parse()
#6 /home/www/.../system/modules/Subcolumns/elements/colsetPart.php(113): Contao\ContentElement->generate()
#7 /home/www/.../system/modules/core/library/Contao/Controller.php(476): FelixPfeiffer\Subcolumns\colsetPart->generate()
#8 /home/www/.../system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 /home/www/.../system/modules/core/modules/Module.php(283): Contao\ModuleArticle->compile()
#10 /home/www/.../system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 /home/www/.../system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#12 /home/www/.../system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 /home/www/.../system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#14 /home/www/.../system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 /home/www/.../index.php(20): Contao\FrontendIndex->run()
#16 {main}`

Es wurde ein update von 3.4.x auf 3.5.8 gemacht. Cache ist geleert.
In der Datenbank sind 4 Spaltensets abgelegt bekinnent mit der ID 2.
ID 1 bit es keine und wird auch nicht auf der Seite eingestetzt.

Danke

**Comment by dmolineus** [comment]
Maybe an error message could be generated instead of an exception being thrown. But not so trivial when using 3rd party extensions as integration level.

**Comment by niebuhrhood** [comment]
Yes, there is something to this.
When editing the form in the backend the error is thrown, too. Backend gets white with error message.
I have to look in the db table tl_form_field?!

**Comment by niebuhrhood** [comment]
So, now you get a simple error message? Like the red ones standard in Contao?
