### ISSUE TITLE
Overwrite column offsets with zero

### ISSUE THREAD

**Issue by rflx** [contao-bootstrap/grid-editor#14]
Hi @dmolineus,
i am missing the 0-offset (zero-offset) setting for resetting offset columns. In this example i would like to reset the offset with `col-lg-offset-0`:
`<div class="col-md-8 col-md-offset-2 col-lg-12 col-lg-offset-0"></div>`

**Workaround** would be to insert `col-*-offset-0` in field for own CSS-class.

Cheers

**Comment by runge-medien** [comment]
Hi @dmolineus, why the error has not been corrected? Or is the project currently stopped? 
@rflx nice! Thank you for this workaround.

Best wishes from germany!

Jannes Runge, Runge Medien

**Comment by dmolineus** [comment]
The project is still maintained. However this bug didn't have a high priority so far especially as there is a workaround for it.
