### ISSUE TITLE
Contao 4-Version?

### ISSUE THREAD

**Issue by Defcon0** [contao-bootstrap/grid-editor#17]
Did you test the module already in Contao 4? Will there be a version in the near future supporting Contao 4?

**Comment by Webstylerin** [comment]
I have the same question. I thought every 3.5-extension will work with Contao 4? I really need this editor.

**Comment by dmolineus** [comment]
For Bootstrap 4 there is the first alpha release. https://github.com/contao-bootstrap/grid
