### ISSUE TITLE
Add support for semantic_html5 2.x

### ISSUE THREAD

**Issue by davidmaack** [contao-bootstrap/grid-editor#18]
In version 2 of https://github.com/menatwork/semantic_html5 the DCA config has changed, so the integration is broken atm. 

Until this issue is fixed, maye a notice in the reamde might be a good idea, some people seems to get confused: https://community.contao.org/de/showthread.php?67671-semantic_html5-unterst%C3%BCtzt-in-Version-2-contao-bootstrap-nicht-mehr

**Comment by dmolineus** [comment]
Support für Contao 3 ist beendet.
