### ISSUE TITLE
Additional Information for be_subcolumns template

### ISSUE THREAD

**Issue by Munsio** [contao-bootstrap/grid-editor#6]
It would be great if i can get additional informations in the be_subcolumns template.

I suggest following:
- total number of rows
- integer with current row number
- the description field

**Comment by MrTool** [comment]
Point 1&2 are out as an PR to #felixpfeiffer/Contao-Subcolumns/pull/31

**Comment by dmolineus** [comment]
V2 won't use Subcolumns anymore. So I won't change anything here.
