### ISSUE TITLE
responsive column resets

### ISSUE THREAD

**Issue by taleteller** [contao-bootstrap/grid-editor#8]
Its me again ;-)

I just came across the issue of [http://getbootstrap.com/css/#grid-responsive-resets](column resets). This ensures correct alignment of flexible height columns when collapsing. This is done by inserting selective clearfix divs between the columns. Here is [another reference](http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-grid-system.php) explaining the issue. 

Since this is part of the bootstrap grid system the editor should handle this as well. As there is no way to automatically decide where to place clearfixes, every column definition in every resolution should get an additional checkbox "force clearfix (Umbruch erzwingen)".

For example, you define a gridset: small 6-6 and medium 4-4-4. This would get you two columns at small and three at medium. Of course, you add way more than three elements in the content, creating several rows. You check the "force clearfix" box on the last column of both grid resolutions. Now the grid-editor appends every two elements `<div class="clearfix visible-sm-block"></div>` and every three elements `<div class="clearfix visible-md-block"></div>` while rendering. That way your grid elements stay in line on resolution changes.

Addendum: I just noticed, the grid editor specifies the same number of colums for all resolutions. limiting its flexiblility. Since the number of columns is not necessary the number ob elements, every resolution should have add/remove buttons instead of having a fixed "number of columns" drowdown.

**Comment by dmolineus** [comment]
> Its me again ;-)
Great, I like such advanced usages and improvement tasks. :)

I know this limitation and considered to add it as well. Adding the checkbox is not the big deal. The challange is to add it to every integration (Subcolumns, SemanticHtml5). So far the expected effort is higher than the gained enhancement for me. That's why it has a low priority so far.

> Addendum: I just noticed, the grid editor specifies the same number of colums for all resolutions. limiting its flexiblility. Since the number of columns is not necessary the number ob elements, every resolution should have add/remove buttons instead of having a fixed "number of columns" drowdown.

I'm not sure if I really understand what you mean. Could you make a new issue for that please and try to explain it again?

**Comment by taleteller** [comment]
> I know this limitation and considered to add it as well. Adding the checkbox is not the big deal. The challange is to add it to every integration (Subcolumns, SemanticHtml5). So far the expected effort is higher than the gained enhancement for me. That's why it has a low priority so far.

Thing is, enforcing the clears is essential to responsibility. In the "wild" you rarely find columns with equal heights. Taking a set of 4 columns, with width of 3 each, changing to width 6 at low resolution gives you two rows by two columns. Having a 1px "taller" column at the wrong place, breaks the grid. Thats already within one simple set adding up to 12 cols. 

Thing also is, you cant "bypass" that problem by getting creative in the backend. The clearfix has to be placed between the closing `</div>` of the last column, and the opening `<div>` of the next one. Yo will end up by leaving the grid editor, coding by hand.

I have no experience with SemanticHtml5, however Bootstrap grids are way more than a table-kind set of `<div>`s. For example the possibility to hide or show columns at specific resolutions are pretty neat. Might be integrations to other system will be a choice of either limiting the features to the smallest subset, or handing over whatever is possible only. Personally I would always go with the features my system is providing. 

> I'm not sure if I really understand what you mean. Could you make a new issue for that please and try to explain it again?

Sure I can do, they are related, without having additional properties on columns you possibly wont notice the issue at all.

**Comment by dmolineus** [comment]
> Thing is, enforcing the clears is essential to responsibility. In the "wild" you rarely find columns with equal heights. Taking a set of 4 columns, with width of 3 each, changing to width 6 at low resolution gives you two rows by two columns. Having a 1px "taller" column at the wrong place, breaks the grid. Thats already within one simple set adding up to 12 cols.

I understand the issue. In the projects I us the grid I only struggled once with that (and fixed it by adding custom html between the columns). So for my personal gain it hasn't a high priority.

> I have no experience with SemanticHtml5, however Bootstrap grids are way more than a table-kind set of <div>s. For example the possibility to hide or show columns at specific resolutions are pretty neat. Might be integrations to other system will be a choice of either limiting the features to the smallest subset, or handing over whatever is possible only. Personally I would always go with the features my system is providing.

The grid editor was created first to extend Subcolumns fixed columns definition. So the features were oriented by Subcolumns. I don't be fixed on any integration. It's just a matter of time and in the end money I have to invest and last but not least try to make it usable for the clients.

> Addendum: I just noticed, the grid editor specifies the same number of colums for all resolutions. limiting its flexiblility. Since the number of columns is not necessary the number ob elements, every resolution should have add/remove buttons instead of having a fixed "number of columns" drowdown.

As far as I see the number of columns can't differ between the different sizes because you have to asign content to each column. But maybe you can make it more clear.

**Comment by dmolineus** [comment]
There's WIP on the develop branch for this issue started in 166ed62854415e26e125941bc2d1effee5b0a56c.

Checklist what's done so far:
- [x] Subcolumns content element
- [ ] Subcolumns form
- [ ] Subcolumns module
- [x] Semantic html5
- [x] Insert tag

**Comment by dmolineus** [comment]
Support for column resetting also added for subcolumns forms (99f1c7a70046d811c62302591745e963973af6cb) and subcolumns module (486c4197f371e0fd1348c597dc72ba29b137f5b3). 

Could you please test each integration if everything works fine. Released it as 1.1.0-rc1.

**Comment by dmolineus** [comment]
Improved in the latests commits. Closing this because feature is there and got no feedback.
